
# python 3.8.8 | torch 1.8.1 | torchvision 0.9.1
FROM pytorch/pytorch:1.8.1-cuda11.1-cudnn8-runtime

# -y：yes，在命令行交互提示中，直接输入 yes
RUN apt-get update && apt-get install vim -y && apt-get install libglib2.0-0 -y && apt install libgl1-mesa-glx -y && apt-get install gcc -y

# create dictory and set as work dictory
RUN mkdir /v0.0.1 && mkdir /v0.0.1/docker_tmp
WORKDIR /v0.0.1
COPY ./data/JoUtil-0.2.12.9-py3-none-any.whl /v0.0.1/docker_tmp

# install python package
RUN pip install -i https://pypi.douban.com/simple \
    flask\
    shapely\
    pycryptodome\
    Cython\
    matplotlib\
    pandas\
    seaborn\
    sklearn\
    yacs\
    prettytable\
    gevent\
    # tensorflow-gpu==1.15.0\   # todo 先不管了，后面线夹倾斜 均压环倾斜 等用到 tenssorflow 的要进行重写
    opencv-python\
    /v0.0.1/docker_tmp/JoUtil-0.2.12.9-py3-none-any.whl

# insert line, check the inference
RUN sed -i "268i \            self.score_thresh = 0.1 if not hasattr(self, 'score_thresh') else self.score_thresh" \
    /opt/conda/lib/python3.8/site-packages/JoTools/../torchvision/models/detection/rpn.py

# remove temp file
RUN rm -r /v0.0.1/docker_tmp

# copy all code to docker
COPY ./data/v0.0.1 /v0.0.1

# change permission
RUN chmod 777 ./ -R

# compile the py
# RUN python3 /v0.0.1/scripts/tools/encrypt.py -end /v0.0.1/lib/detect_libs/,/v0.0.1/lib/JoTools/,/v0.0.1/lib/detect_utils/,/v0.0.1/scripts/dete/ -env /opt/conda/pkgs/python-3.8.8-hdb3f193_4/include/python3.8/ -c





